### ISSUE TITLE
Cookieless tracking

### ISSUE THREAD

**Issue by tw1t611** [beyonk-adventures/svelte-google-analytics#10]
Hi, i am trying to setup cookieless tracking with ga4.
Here is my config:
```js
    <GoogleAnalytics
      properties={["G-HFPDPNYCZ1"]}
      configurations={{
        "G-HFPDPNYCZ1": {
          client_storage: "none",
          anonymize_ip: true,
          cookie_flags: "samesite=none;secure",
        },
      }}
    />
```

Somehow cookies are created. Is that a bug, or isn't it possible to disable all cookies?
![image](https://user-images.githubusercontent.com/13353525/120309424-83cced00-c2d5-11eb-8351-2a21e443b0a0.png)

`samesite=none;secure` seems like the http flag, so could it be, that cookies are just not sent, but created?

The goal is to setup analytics without a need for a cookie banner.
This might not be related to the project. I would be thankful for any hint though.

**Comment by antony** [comment]
I'm afraid this extends beyond my knowledge of google analytics, but maybe somebody else can help.

**Comment by dextermb** [comment]
Based on the article [here](https://goenning.net/2021/02/01/cookieless-google-analytics/) it seems that you should be passing:

```
{ client_storage: 'none', anonymize_ip: true }
```

Feel free to reopen this issue if you are still having issues.
