### ISSUE TITLE
Failed to resolve import "@beyonk/async-script-loader"

### ISSUE THREAD

**Issue by jhwheeler** [beyonk-adventures/svelte-google-analytics#25]
I've installed the package and imported it to my __layout.svelte file (I'm using SvelteKit w/ Svelte v3.34.0), but I get this error on build:

<img width="1041" alt="CleanShot 2022-04-23 at 14 41 38@2x" src="https://user-images.githubusercontent.com/23257850/164883429-2cc516fb-ab77-41d3-b37b-181b2f6910cf.png">

Any idea why the async script loader isn't being resolved?

Thanks!

**Comment by YevhenKap** [comment]
It's simply because `@beyonk/async-script-loader` is defined as a development dependency. You can work around that by installing that package by yourself.

**Comment by jhwheeler** [comment]
Gotcha, thanks!
