### ISSUE TITLE
Misleading documentation for event tracking

### ISSUE THREAD

**Issue by hmaesta** [beyonk-adventures/svelte-google-analytics#7]
README says:

```js
import { ga } from '@beyonk/svelte-google-analytics'

function handleClick () {
    ga.earnVirtualCurrency('SvelteBucks', 50)
}
```

```js
ga.earnVirtualCurrency('SvelteBucks', 50, 'Property Id B')
```

But `ga.earnVirtualCurrency()` doesn't work.
It should be `ga.games.earnVirtualCurrency()` ✅ 

[REPL to reproduce.](https://svelte.dev/repl/e0b826c868aa41379db061c8f63851b7?version=3.35.0)

**Comment by antony** [comment]
whoops!
